const https = require('https');
const fs = require('fs');
const path = require('path');
const EOL = require('os').EOL;

const repo_path = '/aosp-mirror/platform_frameworks_base/master';
const original = {
    hostname: 'raw.githubusercontent.com',
    path: repo_path + '/core/java/android/view/KeyEvent.java',
    method: 'GET',
};
const regex = /public static final int (KEYCODE_[^\s]+)\s*=\s*([0-9]+);/g;
const file = path.resolve(__dirname, '../src/adb/keycode.ts');

const req = https.request(original, function (res) {
    if (res.statusCode !== 200) {
        console.warn('Unable to retrieve KeyEvent.java (HTTP ' + res.statusCode + ')');
        return;
    }
    let raw = Buffer.from('');
    res.on('data', (chunk) => {
        return (raw = Buffer.concat([raw, chunk]));
    });
    return res.on('end', () => {
        const code = raw.toString();
        const date = new Date().toUTCString();
        const typescript = [];
        typescript.push('// Generated by `npm run keycode` on ' + date);
        typescript.push('// KeyEvent.java Copyright (C) 2006 The Android Open Source Project');
        typescript.push('');
        typescript.push('export enum KeyCodes {');
        let match;
        while (match = regex.exec(code)) {
            typescript.push(`    ${match[1]} = ${match[2]},`);            
        }
        typescript.push('}');
        typescript.push('');
        fs.writeFileSync(file, typescript.join(EOL));
        console.log('File ' + file + ' created');
    });
});
req.on('error', (e) => {
    console.error(e.message);
});
return req.end();
